### ISSUE TITLE
Fix clearing Bottle

### ISSUE THREAD

**Issue by pattacini** [vvv17-vision/assignment_closest-blob-fabian-paus#1]
Hi @fabian-paus 

Consider revising [these lines](https://github.com/vvv17-vision/assignment_closest-blob-fabian-paus/blob/master/main.cpp#L198-L199). We've just spotted that you're flooding the network, 'cause the clearing of the Bottle is not correct.

**Comment by fabian-paus** [comment]
Should be fixed with c6be6419d548a0db6d333f0169219cb91e167639
